/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;
import java.sql.SQLException;
import java.util.ArrayList;

import modelo.VO.*;
import Controlador.ControladorRequerimientos;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.*;

/**
 *
 * @author LUIS BOCANEGRA
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    public static final ControladorRequerimientos controlador=new ControladorRequerimientos();
    DefaultTableModel modelo;
    /** Creates new form VentanaPrincipal */
    public VentanaPrincipal() {
        
        initComponents();
        modelo= new DefaultTableModel();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        BtnConsulta1 = new javax.swing.JPanel();
        BtlConsulta1 = new javax.swing.JLabel();
        BtnConsulta2 = new javax.swing.JPanel();
        BtlConsulta2 = new javax.swing.JLabel();
        BtnConsulta3 = new javax.swing.JPanel();
        BtlConsulta3 = new javax.swing.JLabel();
        BtnConsulta4 = new javax.swing.JPanel();
        BtlConsulta5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla1 = new javax.swing.JTable();
        Title = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnConsulta1.setBackground(new java.awt.Color(204, 204, 204));

        BtlConsulta1.setBackground(new java.awt.Color(204, 204, 204));
        BtlConsulta1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtlConsulta1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtlConsulta1.setText("REQUERIMIENTO 2");
        BtlConsulta1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtlConsulta1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtlConsulta1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtlConsulta1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtlConsulta1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout BtnConsulta1Layout = new javax.swing.GroupLayout(BtnConsulta1);
        BtnConsulta1.setLayout(BtnConsulta1Layout);
        BtnConsulta1Layout.setHorizontalGroup(
            BtnConsulta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
            .addGroup(BtnConsulta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BtnConsulta1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(BtlConsulta1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        BtnConsulta1Layout.setVerticalGroup(
            BtnConsulta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
            .addGroup(BtnConsulta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BtnConsulta1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(BtlConsulta1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        bg.add(BtnConsulta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 150, 40));

        BtnConsulta2.setBackground(new java.awt.Color(204, 204, 204));

        BtlConsulta2.setBackground(new java.awt.Color(204, 204, 204));
        BtlConsulta2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtlConsulta2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtlConsulta2.setText("REQUERIMIENTO 1");
        BtlConsulta2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtlConsulta2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtlConsulta2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtlConsulta2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtlConsulta2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout BtnConsulta2Layout = new javax.swing.GroupLayout(BtnConsulta2);
        BtnConsulta2.setLayout(BtnConsulta2Layout);
        BtnConsulta2Layout.setHorizontalGroup(
            BtnConsulta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
            .addGroup(BtnConsulta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BtnConsulta2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(BtlConsulta2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        BtnConsulta2Layout.setVerticalGroup(
            BtnConsulta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
            .addGroup(BtnConsulta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BtnConsulta2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(BtlConsulta2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        bg.add(BtnConsulta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 150, 40));

        BtnConsulta3.setBackground(new java.awt.Color(204, 204, 204));

        BtlConsulta3.setBackground(new java.awt.Color(204, 204, 204));
        BtlConsulta3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtlConsulta3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtlConsulta3.setText("REQUERIMIENTO 3");
        BtlConsulta3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtlConsulta3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtlConsulta3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtlConsulta3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtlConsulta3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout BtnConsulta3Layout = new javax.swing.GroupLayout(BtnConsulta3);
        BtnConsulta3.setLayout(BtnConsulta3Layout);
        BtnConsulta3Layout.setHorizontalGroup(
            BtnConsulta3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
            .addGroup(BtnConsulta3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BtnConsulta3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(BtlConsulta3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        BtnConsulta3Layout.setVerticalGroup(
            BtnConsulta3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
            .addGroup(BtnConsulta3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BtnConsulta3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(BtlConsulta3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        bg.add(BtnConsulta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 150, 40));

        BtnConsulta4.setBackground(new java.awt.Color(204, 204, 204));

        BtlConsulta5.setBackground(new java.awt.Color(204, 204, 204));
        BtlConsulta5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtlConsulta5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtlConsulta5.setText("LIMPIAR");
        BtlConsulta5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtlConsulta5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtlConsulta5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtlConsulta5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtlConsulta5MouseExited(evt);
            }
        });

        javax.swing.GroupLayout BtnConsulta4Layout = new javax.swing.GroupLayout(BtnConsulta4);
        BtnConsulta4.setLayout(BtnConsulta4Layout);
        BtnConsulta4Layout.setHorizontalGroup(
            BtnConsulta4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
            .addGroup(BtnConsulta4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BtnConsulta4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(BtlConsulta5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        BtnConsulta4Layout.setVerticalGroup(
            BtnConsulta4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
            .addGroup(BtnConsulta4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BtnConsulta4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(BtlConsulta5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        bg.add(BtnConsulta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 150, 40));

        Tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Tabla1);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 350, 260));

        Title.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Title.setForeground(new java.awt.Color(51, 51, 255));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("------------------------------------");
        bg.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("RETO 5 GRUPO 14");
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 330, 70));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("LUIS ANGEL BOCANEGRA MENESES");
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 330, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\LUIS BOCANEGRA\\OneDrive\\Imágenes\\mision_tic_2022.png")); // NOI18N
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 290, 190));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\LUIS BOCANEGRA\\OneDrive\\Imágenes\\fondo-blanco-gris-patron-lineas-diagonales_1017-25100.jpg")); // NOI18N
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 620, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtlConsulta1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtlConsulta1MouseClicked
        // TODO add your handling code here:
        modelo.setColumnCount(0);
        modelo.setRowCount(0);
        modelo.addColumn("Nombre material");
        modelo.addColumn("Precio Unidad");
        modelo.addColumn("Total");
        this.Tabla1.setModel(modelo);
        Title.setText("Requerimiento 2 Consulta 4");
        try {
            
            ArrayList<MaterialProyectoVO> respuesta =ControladorRequerimientos.consultarMaterialesProtectos();
            DefaultTableModel tblModel = (DefaultTableModel) Tabla1.getModel();
            for(MaterialProyectoVO registro : respuesta){
                tblModel.addRow(new Object[] {registro.getNombre_material(), registro.getPrecio_Unidad(), registro.getTotal()});
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(),"Error", HEIGHT);
        }

    }//GEN-LAST:event_BtlConsulta1MouseClicked

    private void BtlConsulta1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtlConsulta1MouseEntered
        // TODO add your handling code here:
        BtnConsulta1.setBackground(new Color(153,153,153));
        BtlConsulta1.setForeground(Color.white);
    }//GEN-LAST:event_BtlConsulta1MouseEntered

    private void BtlConsulta1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtlConsulta1MouseExited
        // TODO add your handling code here:
        BtnConsulta1.setBackground(new Color(204,204,204));
        BtlConsulta1.setForeground(Color.black);
    }//GEN-LAST:event_BtlConsulta1MouseExited

    private void BtlConsulta2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtlConsulta2MouseClicked
        // TODO add your handling code here:
        modelo.setColumnCount(0);
        modelo.setRowCount(0);
        modelo.addColumn("Nombre");
        modelo.addColumn("Salario");
        this.Tabla1.setModel(modelo);
        Title.setText("Requerimiento 1 Consulta 1");
        try {
            
            ArrayList<LiderSalariosCartagoVO> respuesta =ControladorRequerimientos.ConsultarLideresCartago();
            DefaultTableModel tblModel = (DefaultTableModel) Tabla1.getModel();
            for(LiderSalariosCartagoVO registro : respuesta){
                tblModel.addRow(new Object[] {registro.getNombre(), registro.getSalario()});
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(),"Error", HEIGHT);
        }
        
        
        
        
    }//GEN-LAST:event_BtlConsulta2MouseClicked

    private void BtlConsulta2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtlConsulta2MouseEntered
        // TODO add your handling code here:
        BtnConsulta2.setBackground(new Color(153,153,153));
        BtlConsulta2.setForeground(Color.white);
    }//GEN-LAST:event_BtlConsulta2MouseEntered

    private void BtlConsulta2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtlConsulta2MouseExited
        // TODO add your handling code here:
        BtnConsulta2.setBackground(new Color(204,204,204));
        BtlConsulta2.setForeground(Color.black);
    }//GEN-LAST:event_BtlConsulta2MouseExited

    private void BtlConsulta3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtlConsulta3MouseClicked
        // TODO add your handling code here:
        modelo.setColumnCount(0);
        modelo.setRowCount(0);
        modelo.addColumn("Nombre");
        modelo.addColumn("Promedio");
        this.Tabla1.setModel(modelo);
        Title.setText("Requerimiento 3 Consulta 5");
        try {
            
            ArrayList<LideresCostoPromVO> respuesta =ControladorRequerimientos.ConsultarLideresCostoProm();
            DefaultTableModel tblModel = (DefaultTableModel) Tabla1.getModel();
            for(LideresCostoPromVO registro : respuesta){
                tblModel.addRow(new Object[] {registro.getNombre(), registro.getPromedio()});
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(),"Error", HEIGHT);
        }
    }//GEN-LAST:event_BtlConsulta3MouseClicked

    private void BtlConsulta3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtlConsulta3MouseEntered
        // TODO add your handling code here:
        BtnConsulta3.setBackground(new Color(153,153,153));
        BtlConsulta3.setForeground(Color.white);
    }//GEN-LAST:event_BtlConsulta3MouseEntered

    private void BtlConsulta3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtlConsulta3MouseExited
        // TODO add your handling code here:
        BtnConsulta3.setBackground(new Color(204,204,204));
        BtlConsulta3.setForeground(Color.black);
    }//GEN-LAST:event_BtlConsulta3MouseExited

    private void BtlConsulta5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtlConsulta5MouseClicked
        // TODO add your handling code here:
        modelo.setColumnCount(0);
        modelo.setRowCount(0);
        Title.setText("---------------------------------");
    }//GEN-LAST:event_BtlConsulta5MouseClicked

    private void BtlConsulta5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtlConsulta5MouseEntered
        // TODO add your handling code here:
        BtnConsulta4.setBackground(new Color(153,153,153));
        BtlConsulta5.setForeground(Color.white);
    }//GEN-LAST:event_BtlConsulta5MouseEntered

    private void BtlConsulta5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtlConsulta5MouseExited
        // TODO add your handling code here:
        BtnConsulta4.setBackground(new Color(204,204,204));
        BtlConsulta5.setForeground(Color.black);
    }//GEN-LAST:event_BtlConsulta5MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtlConsulta1;
    private javax.swing.JLabel BtlConsulta2;
    private javax.swing.JLabel BtlConsulta3;
    private javax.swing.JLabel BtlConsulta5;
    private javax.swing.JPanel BtnConsulta1;
    private javax.swing.JPanel BtnConsulta2;
    private javax.swing.JPanel BtnConsulta3;
    private javax.swing.JPanel BtnConsulta4;
    private javax.swing.JTable Tabla1;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
